### ISSUE TITLE
page Indicator for check_list page is not working

### ISSUE THREAD

**Issue by Bobgy** [Bobgy/audit#3]
As stated, the active page is always page 1.
A variable $page will be transfered to check_list.blade.php to indicate the current page from backend.

**Comment by Bobgy** [comment]
$pageTotal will be passed from backend to indicate the total number of pages.

**Comment by Bobgy** [comment]
@chaiyujin is working on this.

**Comment by chaiyujin** [comment]
Implement dynamic html with JS
