### ISSUE TITLE
login

### ISSUE THREAD

**Issue by mangolzy** [Bobgy/audit#5]
1.
http://localhost/audit/
correct redirection when the userid and pwd are both right,
no corresponding warning msg pop up when either one is not exited or not correct~
2. 
once login, one can accessed the main page simply with the url: http://localhost/audit/main, kind of insecurity~

**Comment by Bobgy** [comment]
1. This is actually part of https://github.com/Bobgy/audit/issues/2.
2. I think it is intended to work this way. Since you have logged in, viewing pages by this url should be okay.

**Comment by Bobgy** [comment]
Error message added.
